### ISSUE TITLE
How to set eosio.token or any contract using eosjs & scatter from front end application at run time

### ISSUE THREAD

**Issue by amolmaid** [EOSIO/eosjs#285]
I am currently working on a _dAPP_ and it's front end we are using _ReactJS_. I wish to add a feature that on button click user could create a new token; For that I need to publish a **eosio.token** contract which internally needs the _permission from user's account_ (so as scatter).
  So could anyone help me with that, as there is no way to use **FS** i.e file system library at front end. So just using eosjs how could I publish a contract ?

**Comment by jcalfee** [comment]
See setCode and setAbi .. If you get the data into an Array it will work.

https://github.com/eosio/eosjs#deploy

**Comment by amolmaid** [comment]
Thanks for the response @jcalfee ,

   But I am kinda confuse here, how can I add a file data into an array, I was able to read .abi file as its a json file, but for .wasm file its ~14k lines of code so how can I add it into an array? And where exactly I should keep the file to read its data? 
   It would be really great if you could enlarge a little.

**Comment by jcalfee** [comment]
Sorry, array buffer..  Probably a Uint8Array or an ArrayBuffer..

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#Buffers_and_views_typed_array_architecture

https://stackoverflow.com/questions/8880571/convert-nodejs-buffer-to-browsers-javascript#16548689

**Comment by wcy1231** [comment]
I meet the same problem with setcode at front end. And I use "new Uint8Array(wasm.data)", but it still not work. Do you have sample code. Thanks a lot ~

**Comment by amolmaid** [comment]
Hi @wcy1231 , I was able to solve this problem after spending quite a long time. 
   Basically I used my own back-end which simply returns the .**wasm** and .**abi** files in buffer format and I am inputting it to the _setcode()_ and _setabi()_ methods on front end by taking user's consent via scatter.

![working setcode](https://user-images.githubusercontent.com/7837458/44658053-d38f7300-aa1c-11e8-8dce-8c414469ce99.png)

You can refer another related issue for this I created - https://github.com/EOSIO/eosjs/issues/300

**Hope this will help.**

**Comment by wcy1231** [comment]
@amolmaid   Thank you.  I fix this just now. Also after a long time. My method is change the wasm to ASCII string. It can work at front end

**Comment by amolmaid** [comment]
@wcy1231 , It would be really great if you could share your code snippet to read the .wasm file from front end directly; and also where exactly to store them ?
It could save my backend call ...

So thanks in advance.

**Comment by wcy1231** [comment]
I also read .wasm from backend

backend: nodedjs
wasm= fs.readFileSync('s.wasm');
res.send(hex2ascii(wasm.toString('Hex')))

frontend:
eos.setcode('myaccount',0,0,wasm)

**Comment by amolmaid** [comment]
Ohh okay !  but nice alternative.

Thanks for the response :)

**Comment by jcalfee** [comment]
It was limited expecting a Buffer (that does not help you) or hex (difficult to convert).  So I released eosjs@16.0.9 that adds support for the Array and Uint8Array.

https://github.com/EOSIO/eosjs-fcbuffer/commit/259e50c9381d86272503b3c888ce148f0f61bc03#diff-3a699a0719518f967e9b2df3f5549e02

**Comment by znebby** [comment]
Thanks but I am still getting the same error message. I pull down the .wasm file using XmlHttpRequest, setting response type as "arraybuffer". Then I convert to Uint8Array.

Same error as with 16.0.8: magic number mismatch. Serialization Error Processing WASM. Magic number loaded ... but was expecting ...

**Comment by jcalfee** [comment]
Does the data start off like this:
```hex
00 61 73 6d ..
```
In text:
```
\u0000asm
```

**Comment by znebby** [comment]
Now I get the error: Contract is already running this version of code (it is most certainly not).

We were also getting this error yesterday, along with the magic number error, depending on which exact format was used

**Comment by jcalfee** [comment]
It takes a major change in the c++ to change the wasm.. Wasm is a sub-set of c++...

**Comment by znebby** [comment]
I'm not sure what you mean?

**Comment by znebby** [comment]
This contract is not currently pushed on that account. We confirmed last night that even if no contact is pushed or a completely different one, that error message would (wrongly) appear. Yesterday it happened when I tried setting the XmlHttpRequest response type to blob.

**Comment by jcalfee** [comment]
This message `Contract is already running this version of code` could potentially include a invalid deployment.  This comes up from time to time while I'm re-deploying changes even though I made changes but it did not functionally affect the wasm.

**Comment by lachlangreenbank** [comment]
@znebby 

Did you have any luck with this?

**Comment by znebby** [comment]
Sorry, have not tried since then. Perhaps it can be done in eosjs2?

**Comment by lachlangreenbank** [comment]
@znebby 

I finally got it working, exactly how @amolmaid  described thoughout.

I was being lazy and using a string version of the wasm inside js file. apparently that was the issue.
As soon as i changed it to being sent as a axios request and reading the resulting buffer, it finally deployed to chain without error. Yet to do ABI and test the full contract but its looking good. if you give it another go let me know any issues you have.

**Comment by simonschmoll** [comment]
Is there any update on this?
I tried to deploy a contract from my frontend, but I also get the magic number mismatch. 

Would it be possible to provide an example of how to deploy a contract from eosjs (only browser) (loading wasm and abi, using setabi and setcode)? Because I think that is a pretty common use case.

That would be really helpful :)

**Comment by lachlangreenbank** [comment]
@simonschmoll 

Are you using eosio.cdt or the old eosiocpp contract compiler?

**Comment by simonschmoll** [comment]
@lachlangreenbank 

I am using eosio.cdt: v1.5.0

**Comment by dominic-healid** [comment]
Any update on this?

Is it really possible to deploy smart contract from browser?

**Comment by tbfleming** [comment]
Maybe we should lock legacy issues to prevent comments about 20 from getting buried.
