### ISSUE TITLE
eosjs token transfer - Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by liebeskind** [EOSIO/eosjs#444]
I'm getting an error whenever I try to transfer EOS using Scatter.  The issue appears to be in eosjs.  Scatter opens up and I successfully sign, but then the transaction fails with the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at ./node_modules/eosjs/dist/eosjs-jsonrpc.js.__values (eosjs-jsonrpc.js:42)
    at arrayToHex (eosjs-jsonrpc.js:58)
    at JsonRpc.<anonymous> (eosjs-jsonrpc.js:323)
    at step (eosjs-jsonrpc.js:36)
    at Object.next (eosjs-jsonrpc.js:17)
    at eosjs-jsonrpc.js:11
    at new Promise (<anonymous>)
    at ./node_modules/eosjs/dist/eosjs-jsonrpc.js.__awaiter (eosjs-jsonrpc.js:7)
    at JsonRpc../node_modules/eosjs/dist/eosjs-jsonrpc.js.JsonRpc.push_transaction (eosjs-jsonrpc.js:316)
    at Api.<anonymous> (eosjs-api.js:411)
    at step (eosjs-api.js:44)
    at Object.next (eosjs-api.js:25)
    at eosjs-api.js:19
    at new Promise (<anonymous>)
    at ./node_modules/eosjs/dist/eosjs-api.js.__awaiter (eosjs-api.js:15)
    at Api../node_modules/eosjs/dist/eosjs-api.js.Api.pushSignedTransaction (eosjs-api.js:409)
    at Api.<anonymous> (eosjs-api.js:399)
    at step (eosjs-api.js:44)
    at Object.next (eosjs-api.js:25)
    at fulfilled (eosjs-api.js:16)
```

Here is the entire file:

```
import React from "react";
import { Api, JsonRpc, JsSignatureProvider } from "eosjs";
import ScatterJS from "scatterjs-core";
import ScatterEOS from "scatterjs-plugin-eosjs2"; // Use eosjs2 if your version of eosjs is > 16

// Using junglehistory here to get actions.  I tried the transaction with https://jungle2.cryptolions.io:443 and got the same error.
const endpoint = "http://junglehistory.cryptolions.io:18888"; // Jungle

const network = {
	blockchain: "eos",
	protocol: "https",
	host: "jungle2.cryptolions.io",
	port: 443,
	chainId: "e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473" // Jungle
};

class EOSIOClient extends React.Component {
	constructor(contractAccount) {
		super(contractAccount);
		this.contractAccount = contractAccount;
		this.account;
		this.eos;

		ScatterJS.plugins(new ScatterEOS());

		try {
			ScatterJS.scatter.connect(this.contractAccount).then(connected => {
				if (!connected) return console.log("Issue Connecting");

				const scatter = ScatterJS.scatter;
				this.scatter = scatter;

				this.requiredFields = {
					accounts: [network]
				};

				this.rpc = new JsonRpc(endpoint);
				window.ScatterJS = null;
			});
		} catch (error) {
			console.log(error);
		}
	}

	login = cb => {
		try {
			this.scatter.getIdentity(this.requiredFields).then(() => {
				this.account = this.scatter.identity.accounts.find(
					x => x.blockchain === "eos"
				);

				this.eos = this.scatter.eos(network, Api, { rpc: this.rpc });
				return cb(this.account);
			});

			window.ScatterJS = null;
		} catch (error) {
			console.log(error);
		}
	};

	transaction = (action, data) => {
		return this.eos.transact(
			{
				actions: [
					{
						account: this.contractAccount,
						name: action,
						authorization: [
							{
								actor: this.account.name,
								permission: this.account.authority
							}
						],
						data: {
							...data
						}
					}
				]
			},
			{
				blocksBehind: 3,
				expireSeconds: 30
			}
		);
	};

	tokenTransfer = data => {
		return this.eos.transact(
			{
				actions: [
					{
						account: "eosio.token",
						name: "transfer",
						authorization: [
							{
								actor: this.account.name,
								permission: this.account.authority
							}
						],
						data: {
							from: this.account.name,
							to: data.to,
							quantity: data.quantity,
							memo: data.memo
						}
					}
				]
			},
			{
				blocksBehind: 3,
				expireSeconds: 30
			}
		);
	};
```

**Comment by liebeskind** [comment]
In case anyone else runs into this issue - it was caused by using the wrong chainId.  Jungle recently change their chainId when they became Jungle2.

**Comment by liebeskind** [comment]
I don't get the error if I set broadcast: false in the options.  However, then the transaction isn't pushed.

**Comment by masaka3620** [comment]
@liebeskind This might be related to a different issue.  Could you post a copy of your lock file, or tell us what version of eosjs it has in there?

**Comment by liebeskind** [comment]
Lock file... will try deleting and reinstall node modules.

```
"eosjs": {
      "version": "20.0.0-beta2.0",
      "resolved": "https://registry.npmjs.org/eosjs/-/eosjs-20.0.0-beta2.0.tgz",
      "integrity": "sha512-lECf0Nbfw25mN1ixHhT1IPuHgqZUJqGUhxDL7bfKzshy8l+hxWjeJW2XxLr7XlpbvDgG6gFqRIIaDB29lK3qGg==",
      "requires": {
        "@types/jest": "^23.3.1",
        "babel-runtime": "^6.26.0",
        "eosjs-ecc": "^4.0.1",
        "text-encoding": "^0.6.4"
      }
    },
    "eosjs-api": {
      "version": "7.0.4",
      "resolved": "https://registry.npmjs.org/eosjs-api/-/eosjs-api-7.0.4.tgz",
      "integrity": "sha512-oLbM39rcyWYkqu6nIEQ50I92yT2vvD7WZPZ3FujbydG2ssR5Re/uSvbkFfZTB02g3I4D+UDUA1jd65HlM7r3MQ==",
      "requires": {
        "camel-case": "^3.0.0",
        "isomorphic-fetch": "^2.2.1"
      }
    },
    "eosjs-ecc": {
      "version": "4.0.4",
      "resolved": "https://registry.npmjs.org/eosjs-ecc/-/eosjs-ecc-4.0.4.tgz",
      "integrity": "sha512-9wAYefts4TidHOu+eN9nAisZdWpUzlUimZrB63oP7+/s4xRNJEn2Vvep2ICRODpxpidbshM1L7WaSYW9oiV5gA==",
      "requires": {
        "bigi": "^1.4.2",
        "browserify-aes": "^1.0.6",
        "bs58": "^4.0.1",
        "bytebuffer": "^5.0.1",
        "create-hash": "^1.1.3",
        "create-hmac": "^1.1.6",
        "ecurve": "^1.0.5",
        "randombytes": "^2.0.5"
      }
    },
```

**Comment by liebeskind** [comment]
Deleting package.lock and node_modules, then reinstalling modules didn't fix the issue.

**Comment by masaka3620** [comment]
We ran into this exact problem due to https://github.com/EOSIO/eosjs/issues/447

We just published a patch that addressed the original problem that was caused by the @edge release referenced in the issue above.  Doing a `yarn install` now might resolve your problem.  You should find that the version of eosjs that you get is `20.0.0-beta2.2`

I believe the chain your using is supported, but if this doesn't resolve the problem, we can rope somebody in who can help with that.

**Comment by liebeskind** [comment]
Thanks @masaka3620.  Looks like updating to 20.0.0-beta2.2 worked.

**Comment by eayllon1** [comment]
I'm getting the same error, using scatterjs-plugin-eosjs2 and eosjs 20.0.0-beta3. Downgrading to beta2.2 does not fix the issue

**Comment by larael96** [comment]
@liebeskind update this issue in your tutorial posted on medium. Which is Scatter integration with eos

**Comment by iamcco** [comment]
Same issue
